services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile.serveur
    container_name: serveur
    privileged: true
    mac_address: 02:42:0A:00:00:0A
    networks:
      lab: 
        ipv4_address: 10.0.0.10
    command: "tail -f /dev/null"

  victime:
    build:
      context: .
      dockerfile: Dockerfile.victime
    container_name: victime
    privileged: true
    mac_address: 02:42:0A:00:00:0B
    networks:
      lab: 
        ipv4_address: 10.0.0.20
    command: "tail -f /dev/null"

  attaquant:
    build:
      context: .
      dockerfile: Dockerfile.attaquant
    container_name: attaquant
    privileged: true
    mac_address: 02:42:0A:00:00:0C
    networks:
      lab: 
        ipv4_address: 10.0.0.30
    volumes:
      - .:/app
    command: "tail -f /dev/null"

networks:
  lab:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
