FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y iproute2 --no-install-recommends ca-certificates net-tools iputils-ping ftp tcpdump && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# USER 1000:1000


# CMD ["tail", "-f", "/dev/null"]
